package security

import (
	"bufio"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"strings"
)

// FetchCloudflareIPs downloads the latest IPv4 and IPv6 ranges
func FetchCloudflareIPs() ([]string, error) {
	var ips []string
	urls := []string{
		"https://www.cloudflare.com/ips-v4",
		"https://www.cloudflare.com/ips-v6",
	}

	for _, u := range urls {
		resp, err := http.Get(u)
		if err != nil {
			return nil, fmt.Errorf("failed to fetch from %s: %v", u, err)
		}
		defer resp.Body.Close()

		scanner := bufio.NewScanner(resp.Body)
		for scanner.Scan() {
			ip := strings.TrimSpace(scanner.Text())
			if ip != "" {
				ips = append(ips, ip)
			}
		}

		if err := scanner.Err(); err != nil {
			return nil, fmt.Errorf("error reading response from %s: %v", u, err)
		}
	}
	return ips, nil
}

// GenerateNginxRealIPConfig writes the config file that NPM will volume-mount
func GenerateNginxRealIPConfig(ips []string, filePath string) error {
	var builder strings.Builder

	builder.WriteString("# Auto-generated by Claviger\n")
	builder.WriteString("# Unmasks Cloudflare IPs so NPM sees the real visitor IP\n\n")

	for _, ip := range ips {
		builder.WriteString(fmt.Sprintf("set_real_ip_from %s;\n", ip))
	}

	builder.WriteString("\nreal_ip_header CF-Connecting-IP;\n")

	// Create the directory if it doesn't exist
	os.MkdirAll("/opt/claviger/proxy", 0755)

	return os.WriteFile(filePath, []byte(builder.String()), 0644)
}

// LockdownUFW purges generic 80/443 rules and ONLY allows Cloudflare IPs
func LockdownUFW(ips []string) error {
	// 1. Delete the dangerous generic open rules if they exist
	exec.Command("ufw", "delete", "allow", "80/tcp").Run()
	exec.Command("ufw", "delete", "allow", "443/tcp").Run()

	// Alternatively, if they added them without /tcp:
	exec.Command("ufw", "delete", "allow", "80").Run()
	exec.Command("ufw", "delete", "allow", "443").Run()

	// 2. Loop through Cloudflare IPs and whitelist them for 80/443
	for _, ip := range ips {
		// e.g., ufw allow proto tcp from 103.21.244.0/22 to any port 80,443
		cmd := exec.Command("ufw", "allow", "proto", "tcp", "from", ip, "to", "any", "port", "80,443")
		if err := cmd.Run(); err != nil {
			fmt.Printf("Warning: Failed to add UFW rule for %s\n", ip)
		}
	}

	// 3. Reload UFW to apply
	return exec.Command("ufw", "reload").Run()
}

func RevertLockdown(activeIPs []string) error {
	// 1. Remove the specific rules we created during lockdown using the EXACT list
	for _, ip := range activeIPs {
		// Skip empty strings just in case
		if strings.TrimSpace(ip) == "" {
			continue
		}
		exec.Command("ufw", "delete", "allow", "proto", "tcp", "from", ip, "to", "any", "port", "80,443").Run()
	}

	// 3. Restore generic open access
	// We add them back just to be sure, or ufw will handle the previous rule existence
	exec.Command("ufw", "allow", "80/tcp").Run()
	exec.Command("ufw", "allow", "443/tcp").Run()

	// 4. Clear out the Nginx config so it's empty again
	// os.WriteFile("/opt/claviger/proxy/cloudflare_ips.conf", []byte(""), 0644)

	// 5. Final reload to clean the state
	return exec.Command("ufw", "reload").Run()
}
