// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function Connect():Promise<void>;

export function Disconnect():Promise<void>;

export function GenerateRequest():Promise<string>;

export function GetTunnelState():Promise<string>;

export function GetVault():Promise<config.ClientVault>;

export function ProcessApproval(arg1:string):Promise<void>;

export function RemoveProfile(arg1:string):Promise<void>;

export function RenameProfile(arg1:string,arg2:string):Promise<void>;

export function SetActiveProfile(arg1:string):Promise<void>;

export function ToggleGlobalRouting(arg1:boolean):Promise<void>;
