// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckApproval() {
  return window['go']['main']['App']['CheckApproval']();
}

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function Enroll(arg1, arg2) {
  return window['go']['main']['App']['Enroll'](arg1, arg2);
}

export function GetVault() {
  return window['go']['main']['App']['GetVault']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}
