// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function CheckApproval():Promise<string>;

export function Connect():Promise<void>;

export function Disconnect():Promise<void>;

export function Enroll(arg1:string,arg2:string):Promise<void>;

export function GetVault():Promise<config.ClientVault>;

export function IsConnected():Promise<boolean>;

export function LeaveNetwork():Promise<void>;
