// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GenerateRequest() {
  return window['go']['main']['App']['GenerateRequest']();
}

export function GetTunnelState() {
  return window['go']['main']['App']['GetTunnelState']();
}

export function GetVault() {
  return window['go']['main']['App']['GetVault']();
}

export function LeaveNetwork() {
  return window['go']['main']['App']['LeaveNetwork']();
}

export function ProcessApproval(arg1) {
  return window['go']['main']['App']['ProcessApproval'](arg1);
}

export function ToggleGlobalRouting(arg1) {
  return window['go']['main']['App']['ToggleGlobalRouting'](arg1);
}
