// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GenerateRequest() {
  return window['go']['main']['App']['GenerateRequest']();
}

export function GetTunnelState() {
  return window['go']['main']['App']['GetTunnelState']();
}

export function GetVault() {
  return window['go']['main']['App']['GetVault']();
}

export function ProcessApproval(arg1) {
  return window['go']['main']['App']['ProcessApproval'](arg1);
}

export function RemoveProfile(arg1) {
  return window['go']['main']['App']['RemoveProfile'](arg1);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['App']['SetActiveProfile'](arg1);
}

export function ToggleGlobalRouting(arg1) {
  return window['go']['main']['App']['ToggleGlobalRouting'](arg1);
}
