package auth

import (
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
)

// GenerateRandomHex creates a cryptographically secure random hex string
func GenerateRandomHex(bytes int) (string, error) {
	b := make([]byte, bytes)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("failed to read random bytes: %v", err)
	}
	return hex.EncodeToString(b), nil
}

// GenerateInviteToken creates the standard 'clav-xyz' connection string
func GenerateInviteToken() string {
	hexStr, err := GenerateRandomHex(8) // 8 bytes = 16 hex characters
	if err != nil {
		return "clav-err-fallback" // Extremely rare fallback
	}
	return "clav-" + hexStr
}

// AdminPayload defines what gets packed into the Setup Command's Base64 token
type SmartTokenPayload struct {
	Token     string `json:"token"`
	ServerIP  string `json:"server_ip"`
	HubPort   string `json:"hub_port"`
	ServerKey string `json:"server_key"`
}

// GenerateSmartToken packs the raw invite, server details, and public key into one base64 string
func GenerateSmartToken(inviteToken, serverIP, hubPort, serverKey string) (string, error) {
	payload := SmartTokenPayload{
		Token:     inviteToken,
		ServerIP:  serverIP,
		HubPort:   hubPort,
		ServerKey: serverKey, // NEW
	}

	jsonData, err := json.Marshal(payload)
	if err != nil {
		return "", err
	}

	// Encode to Base64 so it's a single, easy-to-copy string
	return base64.StdEncoding.EncodeToString(jsonData), nil
}

// ConnectionRequest is the payload generated by the Client asking to join the network.
type ConnectionRequest struct {
	Type      string `json:"type"` // Must be "request"
	PublicKey string `json:"public_key"`
	Hostname  string `json:"hostname"`
	Platform  string `json:"platform"`
	DeviceID  string `json:"device_id"`
}

// ConnectionApproval is the payload generated by the Server granting access.
type ConnectionApproval struct {
	Type           string `json:"type"` // Must be "approval"
	Role           string `json:"role"`
	AssignedIP     string `json:"assigned_ip"`
	ServerPubKey   string `json:"server_public_key"`
	ServerEndpoint string `json:"server_endpoint"`
}

// DecodeConnectionRequest takes the Base64 string from the user and turns it into a Go struct.
func DecodeConnectionRequest(tokenString string) (*ConnectionRequest, error) {
	// 1. Decode Base64
	decodedBytes, err := base64.StdEncoding.DecodeString(tokenString)
	if err != nil {
		return nil, fmt.Errorf("invalid token format: not valid base64")
	}

	// 2. Parse JSON
	var req ConnectionRequest
	if err := json.Unmarshal(decodedBytes, &req); err != nil {
		return nil, fmt.Errorf("invalid token format: corrupted json payload")
	}

	// 3. Strict Validation
	if req.Type != "request" {
		return nil, fmt.Errorf("invalid token type: expected connection request")
	}
	if req.PublicKey == "" {
		return nil, fmt.Errorf("invalid token: missing wireguard public key")
	}

	return &req, nil
}

// EncodeConnectionApproval takes the Server's approval data and packs it into a Base64 string for the user.
func EncodeConnectionApproval(approval *ConnectionApproval) (string, error) {
	// 1. Enforce the type
	approval.Type = "approval"

	// 2. Convert to JSON
	jsonData, err := json.Marshal(approval)
	if err != nil {
		return "", fmt.Errorf("failed to encode approval token: %v", err)
	}

	// 3. Encode to Base64
	tokenString := base64.StdEncoding.EncodeToString(jsonData)
	return tokenString, nil
}
